@startuml test


actor User
participant "Application" as App 
participant "Flask" as Server
participant "Client" as Client
participant "Pinecone Vector Database" as Database

User -> App: User inputs general Wentworth question into text field
App -> Server: POST request is sent to backend Flask server
Server -> Client: Server responds to GET request sent for question retrieval
Client -> Database: Cosine similarity search executed with embeddings from Pinecone
Database -> Client: Top relevant documents are returned
Client -> Server: Invokes AI21 LLM to create relevant response; \n POST request sent with response to Flask server 
Server -> App: Flask server responds to GET request sent from frontend \n to retrieve answer to question
App -> User: LLM generated answer is displayed to user
@enduml